<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://codex.wordpress.org/Child_Themes
 */

if (!function_exists('uptime_child_enqueue_styles')) {
    function tommusrhodus_generate_skin_uptime_child()
    {

        $bg_dark = get_theme_mod('bg_dark', '#212529');

        $logo_height = str_replace('px', '', get_theme_mod('logo_height', '26px')) . 'px';
        $logo_width = str_replace('px', '', get_theme_mod('logo_width', 'auto'));
        if ($logo_width != 'auto') {
            $logo_width = $logo_width . 'px';
        }
        $link_text = get_theme_mod('link_text', '#3755BE');

        $skin = '
        
            a {
                color: ' .$link_text. '
            }
        
            .navbar-brand img {
				max-height: ' . $logo_height . ';
				width: ' . $logo_width . ';
			}
			
            .navbar-brand svg {
				max-height: ' . $logo_height . ';
				width: ' . $logo_width . ';
			}    
            
            .footer-strip {
                background: '. $bg_dark . ' !important;
            }			    
    ';

        return $skin;
    }

    function uptime_child_enqueue_styles()
    {
        wp_enqueue_style('uptime-style', get_template_directory_uri() . '/style.css');
        wp_enqueue_style('uptime-child-style',
            get_stylesheet_directory_uri() . '/style.css',
            array('uptime-style'),
            wp_get_theme()->get('Version')
        );
        wp_enqueue_style('style-spg', get_stylesheet_directory_uri() . '/css/style-spg.css');

        wp_add_inline_style('uptime-child-style', tommusrhodus_generate_skin_uptime_child());

        wp_register_script('scripts-spg', get_stylesheet_directory_uri() . '/js/scripts.js');
        wp_enqueue_script('scripts-spg' );
        wp_localize_script( 'scripts-spg', 'wp_var',
            array( 'ajax_url' => admin_url( 'admin-ajax.php' ) ) );

    }

    add_action('wp_enqueue_scripts', 'uptime_child_enqueue_styles', 111);
}

if (!function_exists('uptime_child_get_custom_logo')) {
    function uptime_child_get_custom_logo()
    {

        $site_logo = '';
        if( $custom_logo_id = get_theme_mod('custom_logo') ){
            $site_logo = get_attached_file( $custom_logo_id );
        }

        if( mime_content_type($site_logo) == 'image/svg+xml' ) {
            $custom_logo = '
            <span class="site-logo">
              {{home_logo_src}}
            </span>            
            ';

            $custom_logo = str_replace('{{home_logo_src}}', file_get_contents($site_logo), $custom_logo);
        } else {
            $custom_logo = '<img class="d-inline-block align-top site-logo" src="{{home_logo_src}}" alt="Softwareplanetgroup">';

            $custom_logo = str_replace('{{home_logo_src}}', wp_get_attachment_url($custom_logo_id), $custom_logo);
        }


        $html =  '
        <a class="navbar-brand" href="{{home_url}}">            
              {{custom_logo}}                        
        </a>';

        $html = str_replace('{{custom_logo}}', $custom_logo, $html);
        return str_replace('{{home_url}}', get_home_url(), $html);
    }

    add_action('get_custom_logo', 'uptime_child_get_custom_logo');
}

function wp_upload_mimes($mimes) {
    $mimes['svg'] = 'image/svg+xml';
    return $mimes;
}
add_filter('upload_mimes', 'wp_upload_mimes');


if (!function_exists('uptime_child_widget_nav_menu_args')) {
    function uptime_child_widget_nav_menu_args($nav_menu_args, $nav_menu, $args, $instance)
    {
        $nav_menu_args['menu_class'] = 'nav';
        $nav_menu_args['depth'] = 2;

        return $nav_menu_args;
    }
    add_filter( 'widget_nav_menu_args', 'uptime_child_widget_nav_menu_args' );
}

if (!function_exists('uptime_child_add_footer_layouts')) {
    function uptime_child_add_footer_layouts($options) {

        $options['spg'] = 'Default SPG';

        return $options;
    }
    add_filter( 'tommusrhodus_add_footer_layouts', 'uptime_child_add_footer_layouts' );
}

if (!function_exists('uptime_child_init_elementor_blocks')) {
    function uptime_child_init_elementor_blocks() {

        require_once(__DIR__ . '/blocks/Widget_SPG_Contact_Us_Form_Block.php');
    }
    add_action('elementor/widgets/widgets_registered', 'uptime_child_init_elementor_blocks', 26);
}

if (!function_exists('uptime_child_customize_register')) {

    $option_priority  = 300;

    function theme_option_add_controll($wp_customize, $theme_option_var = array()) {
        global $option_priority;

        $theme_option = array_merge(
            array(
                'default'       => '',
                'type'          => 'text',

                'option_type' => 'theme_mod', // you can also use 'option'
                'description' => '',
                'transport'     => 'postMessage'
            ),
            $theme_option_var
        );

        $wp_customize->add_setting(
            $theme_option['id'],
            array(
                'default' => $theme_option['default'],
                'type' => $theme_option['option_type'],
                'capability' => 'edit_theme_options'
            )
        );

        $wp_customize->add_control( new WP_Customize_Control(
            $wp_customize,
            $theme_option['id'],
            array(
                'label'      => __( $theme_option['title'], 'textdomain' ),
                'description' => __( $theme_option['description'], 'textdomain' ),
                'settings'   => $theme_option['id'],
                'priority'   => $option_priority++,
                'section'    => $theme_option['section'],
                'type'       => $theme_option['type'],
            )
        ) );

    }

    function uptime_child_customize_register( WP_Customize_Manager $wp_customize ) {

        theme_option_add_controll(
            $wp_customize,
            array(
                'id'            => 'footer_budges',
                'section'       => 'footer',

                'title'         => esc_html__( 'Footer budges', 'uptime' ),

                'default'   => '',
                'type'      => 'textarea',
            )
        );

        theme_option_add_controll(
            $wp_customize,
            array(
                'id'            => 'footer_buttons',
                'section'       => 'footer',

                'title'         => esc_html__( 'Footer buttons', 'uptime' ),

                'default'   => '',
                'type'      => 'textarea',
            )
        );

        theme_option_add_controll(
            $wp_customize,
            array(
                'id'            => 'link_text',
                'section'       => 'theme_colors',

                'title'         => esc_html__( 'Link Text Color', 'uptime' ),

                'default'   => '#3755BE',
                'type'      => 'color',
            )
        );

        theme_option_add_controll(
            $wp_customize,
            array(
            'id'            => 'mail_receiver',
            'section'       => 'title_tagline',

            'title'         => esc_html__( 'Mail receiver', 'uptime' ),
            'description'   => esc_html__( 'Set email to receive messages', 'uptime' ),

            'option_type'   => 'option'
            )
        );

        theme_option_add_controll(
            $wp_customize,
            array(
                'id'        => 'logo_width',
                'section'   => 'header',

                'title'     => esc_html__( 'Logo Width', 'uptime' ),
                'description'   => esc_html__( 'Set logo width (default auto)', 'uptime' ),

                'type'      => 'text',
                'default'   => 'auto',
            )
        );

    }

    add_action( 'customize_register', 'uptime_child_customize_register', 500 );
}

add_action( 'wp_ajax_send_mail', 'wpd_ajax_send_mail' );
add_action( 'wp_ajax_nopriv_send_mail', 'wpd_ajax_send_mail' );
function wpd_ajax_send_mail() {

    $body = json_decode(file_get_contents( 'php://input' ), true);

    $mailType = $body['mailType'];
    $form_data = $body['form_data'];

    $headers     = array(
        'MIME-Version: 1.0',
        'Content-Type: text/html; charset=iso-8859-1',
        'From: SPG Website <request@softwareplanetgroup.com>',
    );
    $htmlContent = '';

    if ( $mailType == 'contact_form_message' ) {
        fill_contact_form_message_mail( $form_data, $htmlContent );
    }

    $result = false;
    try {
        $result = wp_mail( get_option( 'mail_receiver' ),
            'New Message Enquiry from SPG Website - ' . date( "h:i d-M-Y" ),
            $htmlContent,
            implode( "\r\n", $headers ) );

    } catch ( Exception $e ) {
        echo json_encode( array( 'result' => false, 'error' => $e->getMessage() ) );
        echo 'Caught exception: ', $e->getMessage(), "\n";
    }

    echo json_encode( array( 'result' => $result ) );
    wp_die();
}

function fill_contact_form_message_mail($form_data, &$htmlContent ) {

    $mailTemplateFile = __DIR__ . "/mailTemplate.html";
    if ( file_exists( $mailTemplateFile ) ) {
        $htmlContent = file_get_contents( $mailTemplateFile );
        $htmlContent = str_replace( "{{template_directory_uri}}", get_stylesheet_directory_uri(), $htmlContent );
        $htmlContent = str_replace( "{{site_url}}", get_site_url(), $htmlContent );
        $htmlContent = str_replace( "{{contactInformation}}", '', $htmlContent );

        $htmlContent = str_replace( '{{contact_form_name}}', $form_data['name'], $htmlContent );
        $htmlContent = str_replace( '{{contact_form_email}}', $form_data['email'], $htmlContent );
        $htmlContent = str_replace( '{{contact_form_message}}', str_replace("\n\r", '<br><br>', $form_data['message']), $htmlContent );

    }

}

if (!function_exists('uptime_child_add_svg_icons')) {
    add_action('tommusrhodus_add_svg_icons', 'uptime_child_add_svg_icons');

    function uptime_child_add_svg_icons($icons) {
        return array_merge($icons, array('spg_Java' => '<svg class="icon" width="24px" height="24px" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M11.4 9H4.13104C4.02099 9 3.91153 9.01481 3.80612 9.04395C3.20797 9.20933 2.86854 9.79029 3.04799 10.3416L5.52001 17.9357C5.80698 18.8173 6.68743 19.4211 7.68612 19.4211H13.3668C14.3655 19.4211 15.246 18.8173 15.5329 17.9357L16.163 16H18.6C20.5158 16 22 14.3941 22 12.5C22 10.6268 20.6102 9 18.6 9H16.9219H11.4ZM16.8141 14L17.7906 11H18.6C19.3898 11 20 11.6118 20 12.5C20 13.3673 19.3351 14 18.6 14H16.8141Z" fill="#000000"/>
<path opacity="0.3" d="M7.45755 5.53064L8.01277 7.19628C8.16228 7.64483 8.58205 7.94739 9.05487 7.94739C9.80465 7.94739 10.3341 7.21284 10.097 6.50154L9.7685 5.51612C9.5553 4.87652 9.71919 4.17138 10.1926 3.69136L10.8932 2.98105C11.3286 2.53951 11.2607 1.81704 10.7403 1.47976C10.3245 1.21032 9.76132 1.28639 9.44416 1.66699L7.81847 3.61782C7.37506 4.14991 7.23852 4.87355 7.45755 5.53064Z" fill="#000000"/>
<path opacity="0.3" d="M11.3523 5.53064L11.9075 7.19628C12.057 7.64483 12.4768 7.94739 12.9496 7.94739C13.6994 7.94739 14.2288 7.21284 13.9917 6.50154L13.6633 5.51612C13.4501 4.87652 13.6139 4.17138 14.0874 3.69136L14.7879 2.98105C15.2234 2.53951 15.1554 1.81704 14.635 1.47976C14.2193 1.21032 13.6561 1.28639 13.3389 1.66699L11.7132 3.61782C11.2698 4.14991 11.1333 4.87355 11.3523 5.53064Z" fill="#000000"/>
<path opacity="0.3" d="M4 21H17C17.5523 21 18 21.4477 18 22C18 22.5523 17.5523 23 17 23H4C3.44771 23 3 22.5523 3 22C3 21.4477 3.44771 21 4 21Z" fill="#000000"/>
</svg>'));
    }
}